### ISSUE TITLE
Python dependencies

### ISSUE THREAD

**Issue by kihyuk-nam** [traindb-project/traindb#29]
As every traindb user may have been thinking, 
the python models' dependencies seems to hold back the traindb codes (java). 
For example, trsql builds and runs without errors, while tablegan.py do not.
Matching and suggesting perfect package combinations of models, which requires a lot of labour, 
is technically not related to traindb.

My suggestion is that the model runner would not assume that the model dependencies are resolved.
Instead, the runner could launch them through common interfaces such as container or http. 
There could be other options and it would be great if we can discuss possible solutions here.

**Comment by taewhi** [comment]
ML models may have different required packages and dependencies.
It would be best to create an execution environment where all models can be done, but we do not assume which models are used.
Users can also add their own models.
We need a way to prepare the execution environment by including requirements for each model.

**Comment by taewhi** [comment]
For now, I added requirements.txt at traindb-project/traindb-model@1617eaa8caaf604b23e1cc61d3a2e8b1da51ca5c
It will be supported to run models remotely using containers or other interfaces.
